name: Sparrowhawk Project
description: Creating and Blogging About FOSS
meta_description: "Official Sparrowhawk Project GitHub Pages site. Creating and Writing about FOSS"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /index.html
domain_name: "http://sparrowharkproject.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ron Becker"

# Disqus config
disqus-shortname: ""
